name: .NET Core

on:
  push:
    branches: [ release ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore src/LSHDotNet/
    - name: Build
      run: dotnet build --configuration Release --no-restore src/LSHDotNet/
    - name: Test 
      run: dotnet test --no-restore --verbosity normal src/LSHDotNet/
    - name: Pack with dotnet
      run: dotnet pack src/LSHDotNet/LSHDotNet/LSHDotNet.csproj --output nuget-packages --configuration Release
    - name: Push with dotnet
      run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json